apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  DB_USER: cG9zdGdyZXM= # postgres
  DB_PASSWORD: cG9zdGdyZXM= # postgres
  DB_NAME: cG9zdGdyZXM= # postgres
  DB_HOST: cG9zdGdyZXMtc2VydmljZQ== # postgres-service
  DB_PORT: NTQzMg== # 5432